1 Chronicles 2: Fix typo in markirs_daughter
Fix a typo in 1 Chronicles 2. markirs_daughter should be
makirs_daughter. This resulted in the following chron test failure:

ERROR: invalid event: begin(marriage(perezs_hezron,markirs_daughter))

Fixes: 2ff9b4eff5de ("Add 1 Chronicles 2")
Signed-off-by: James Hogan <james@albanarts.com>